version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.24.4

jobs:
  lint-test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod tidy
      - run:
          name: Lint
          command: go vet ./...

      - run:
          name: Install envtest tools and download control-plane binaries
          command: |
            go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
            setup-envtest use 1.33.0 --os linux --arch amd64 --bin-dir ./testbin

      - run:
          name: Run Integration Tests
          command: |
            export KUBEBUILDER_ASSETS=$(pwd)/testbin
            go test ./internal/controller -v

  docker-build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            make docker-buildx IMG=docker.io/yemiwebby/namespace-auto-labeler:latest

workflows:
  build-and-deploy:
    jobs:
      - lint-test
      - docker-build:
          requires:
            - lint-test
